version: '3.8'

services:
  app:
    container_name: nestjs_app
    build:
      context: .
    ports:
      - '3030:3030'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./.env
